### ISSUE TITLE
Compile error occurs as update to latest version

### ISSUE THREAD

**Issue by nices0325** [PowerBroker2/ELMduino#72]
Hello PowerBroker!! 
First of all, Thank you for the awesome library!
I was using elmduino v2.4.1

As I upadate to the lastest version of the library, compile error occurs.. what have changed of the new one..

I have found some changes in the sketch --> if (!myELM327.begin(ELM_PORT, true, 2000))

then this is compile error message
var/folders/p2/dhg40lgx0wbgyhps7633fj540000gn/T/arduino_build_940350/sketch/ELMDUINO_SD_TFT_GYRO_DUE_CUR_PRE_STATUS.ino.cpp.o:(.literal._Z5setupv+0xd4): undefined reference to `ELM327::begin(Stream&, bool const&, unsigned short const&, char const&, unsigned short const&)'
/var/folders/p2/dhg40lgx0wbgyhps7633fj540000gn/T/arduino_build_940350/sketch/ELMDUINO_SD_TFT_GYRO_DUE_CUR_PRE_STATUS.ino.cpp.o: In function `setup()':
/Users/jojaehyeong/Documents/Arduino/libraries/MPU6050/MPU6050_6Axis_MotionApps_V6_12.h:583: undefined reference to `ELM327::begin(Stream&, bool const&, unsigned short const&, char const&, unsigned short const&)'
collect2: error: ld returned 1 exit status

**Comment by PowerBroker2** [comment]
Update to the latest version of the library

**Comment by nices0325** [comment]
https://pastebin.com/R2CDHYAM

this is my sketch. I'm using esp32 board with this library.. when I update to 2.5.4 version compile error occurs.. I'm not sure what have changed with this new version.. I just exchange the src folder to my existing library thank you very much

**Comment by PowerBroker2** [comment]
1.) Does your ESP32 have bluetooth? If so, why not use the built-in bluetooth functionality of the ESP32 instead of using a UART?
2.) I can't get your code to compile due to the many atypical and hard to find libraries you're using. To simplify things, test the appropriate [example sketch](https://github.com/PowerBroker2/ELMduino/tree/master/examples) and see if it compiles for you. If not, we have a problem, if the example compiles, you need to check your project sketch for inconsistencies
